name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: Node.js'
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.13.0
      - name: 'Setup: update npm'
        run: npm install -g npm
      - name: 'Setup: Java 17'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: 'Setup: check tools'
        run: |
          node -v
          npm -v
          java -version
  eat:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Say Hello to eat'
        run: |
          echo "Hello Eat"
  drink:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Say Hello to drink'
        run: |
          echo "Hello Drink"